const issues = [
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/63',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/63/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/63/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/63/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/63',
    id: 241180398,
    number: 63,
    title: 'Application mobile groupe 1',
    user: {
      login: 'Madorakkusu',
      id: 11974574,
      avatar_url: 'https://avatars2.githubusercontent.com/u/11974574?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/Madorakkusu',
      html_url: 'https://github.com/Madorakkusu',
      followers_url: 'https://api.github.com/users/Madorakkusu/followers',
      following_url: 'https://api.github.com/users/Madorakkusu/following{/other_user}',
      gists_url: 'https://api.github.com/users/Madorakkusu/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Madorakkusu/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Madorakkusu/subscriptions',
      organizations_url: 'https://api.github.com/users/Madorakkusu/orgs',
      repos_url: 'https://api.github.com/users/Madorakkusu/repos',
      events_url: 'https://api.github.com/users/Madorakkusu/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Madorakkusu/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [

    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-07-07T07:27:50Z',
    updated_at: '2017-07-07T07:28:36Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/pulls/63',
      html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/63',
      diff_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/63.diff',
      patch_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/63.patch',
    },
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/61',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/61/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/61/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/61/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/61',
    id: 241173932,
    number: 61,
    title: 'groupe 2 - application mobile',
    user: {
      login: 'GoupyVirgil',
      id: 10058330,
      avatar_url: 'https://avatars1.githubusercontent.com/u/10058330?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/GoupyVirgil',
      html_url: 'https://github.com/GoupyVirgil',
      followers_url: 'https://api.github.com/users/GoupyVirgil/followers',
      following_url: 'https://api.github.com/users/GoupyVirgil/following{/other_user}',
      gists_url: 'https://api.github.com/users/GoupyVirgil/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/GoupyVirgil/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/GoupyVirgil/subscriptions',
      organizations_url: 'https://api.github.com/users/GoupyVirgil/orgs',
      repos_url: 'https://api.github.com/users/GoupyVirgil/repos',
      events_url: 'https://api.github.com/users/GoupyVirgil/events{/privacy}',
      received_events_url: 'https://api.github.com/users/GoupyVirgil/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [

    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-07-07T06:54:24Z',
    updated_at: '2017-07-07T06:54:24Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/pulls/61',
      html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/61',
      diff_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/61.diff',
      patch_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/61.patch',
    },
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/60',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/60/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/60/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/60/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/60',
    id: 241009699,
    number: 60,
    title: 'Groupe8 theming',
    user: {
      login: 'Christo92',
      id: 15634829,
      avatar_url: 'https://avatars3.githubusercontent.com/u/15634829?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/Christo92',
      html_url: 'https://github.com/Christo92',
      followers_url: 'https://api.github.com/users/Christo92/followers',
      following_url: 'https://api.github.com/users/Christo92/following{/other_user}',
      gists_url: 'https://api.github.com/users/Christo92/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Christo92/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Christo92/subscriptions',
      organizations_url: 'https://api.github.com/users/Christo92/orgs',
      repos_url: 'https://api.github.com/users/Christo92/repos',
      events_url: 'https://api.github.com/users/Christo92/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Christo92/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [

    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-07-06T16:12:56Z',
    updated_at: '2017-07-06T16:12:56Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/pulls/60',
      html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/60',
      diff_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/60.diff',
      patch_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/60.patch',
    },
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/59',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/59/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/59/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/59/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/59',
    id: 240996870,
    number: 59,
    title: 'Hetic challenge',
    user: {
      login: 'ThomasAdFab',
      id: 15869420,
      avatar_url: 'https://avatars3.githubusercontent.com/u/15869420?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/ThomasAdFab',
      html_url: 'https://github.com/ThomasAdFab',
      followers_url: 'https://api.github.com/users/ThomasAdFab/followers',
      following_url: 'https://api.github.com/users/ThomasAdFab/following{/other_user}',
      gists_url: 'https://api.github.com/users/ThomasAdFab/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ThomasAdFab/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ThomasAdFab/subscriptions',
      organizations_url: 'https://api.github.com/users/ThomasAdFab/orgs',
      repos_url: 'https://api.github.com/users/ThomasAdFab/repos',
      events_url: 'https://api.github.com/users/ThomasAdFab/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ThomasAdFab/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [

    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-07-06T15:31:52Z',
    updated_at: '2017-07-07T07:51:01Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/pulls/59',
      html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/59',
      diff_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/59.diff',
      patch_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/59.patch',
    },
    body: "Il manque quelques bouts de code qu'on ajoutera ce soir pour avoir une liste des images sauvegardées (les images apparaitront en dur)",
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/58',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/58/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/58/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/58/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/58',
    id: 240635206,
    number: 58,
    title: 'Fix',
    user: {
      login: 'Chibibunker',
      id: 10058261,
      avatar_url: 'https://avatars2.githubusercontent.com/u/10058261?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/Chibibunker',
      html_url: 'https://github.com/Chibibunker',
      followers_url: 'https://api.github.com/users/Chibibunker/followers',
      following_url: 'https://api.github.com/users/Chibibunker/following{/other_user}',
      gists_url: 'https://api.github.com/users/Chibibunker/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Chibibunker/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Chibibunker/subscriptions',
      organizations_url: 'https://api.github.com/users/Chibibunker/orgs',
      repos_url: 'https://api.github.com/users/Chibibunker/repos',
      events_url: 'https://api.github.com/users/Chibibunker/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Chibibunker/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [

    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-07-05T12:30:15Z',
    updated_at: '2017-07-05T12:30:15Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/pulls/58',
      html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/58',
      diff_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/58.diff',
      patch_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/58.patch',
    },
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/57',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/57/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/57/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/57/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/57',
    id: 238792453,
    number: 57,
    title: 'plug unit tests in continuous integration pipeline',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 635113774,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/continuous%20integration',
        name: 'continuous integration',
        color: 'f9d0c4',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-27T09:38:22Z',
    updated_at: '2017-06-27T09:38:39Z',
    closed_at: null,
    body: 'Spec: \r\nensure every unit tests are run and passed before each integration on master branch\r\n\r\nStory size(S/M/L/XL): S\r\n\r\nAcceptance criteria:\r\n* check a default unit test is executed and passed after each integration\r\n* run every unit tests in continuous integration pipeline\r\n\r\n',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/56',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/56/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/56/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/56/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/56',
    id: 238790335,
    number: 56,
    title: 'prepare continuous integration pipeline',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 635113774,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/continuous%20integration',
        name: 'continuous integration',
        color: 'f9d0c4',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-27T09:30:35Z',
    updated_at: '2017-06-27T09:33:52Z',
    closed_at: null,
    body: 'Spec: ease integration and prevent regressions of the new contributions on mobile application\r\n\r\nStory size(S/M/L/XL): M\r\n\r\nAcceptance criteria:\r\n* create hook before each github integration on master branch \r\n* list tools that will be included in continuous integration pipeline\r\n* update integration process documentation ',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/55',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/55/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/55/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/55/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/55',
    id: 238787089,
    number: 55,
    title: 'Define our DICOM export format',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 220189045,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/critical',
        name: 'critical',
        color: 'F20723',
        default: false,
      },
      {
        id: 265844218,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/data',
        name: 'data',
        color: '009800',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 1,
    created_at: '2017-06-27T09:19:05Z',
    updated_at: '2017-06-27T09:47:35Z',
    closed_at: null,
    body: 'Spec:\r\nDefine our own DICOM export format relying on echography DICOM norms\r\n\r\n!Need strong experience in medical imaging and DICOM norm standard!\r\n\r\nStory size(S/M/L/XL): L\r\n\r\nAcceptance criteria: \r\n* State of the art in DICOM export format for ultra portable scanner\r\n* create internal DICOM export format documentation \r\n* Draft of the DICOM Conformance statements document - https://en.wikipedia.org/wiki/DICOM',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/54',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/54/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/54/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/54/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/54',
    id: 238784271,
    number: 54,
    title: 'Monitor probe communication',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 429061095,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/feature%20request',
        name: 'feature request',
        color: '8cf073',
        default: false,
      },
      {
        id: 635100081,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/probe_communication',
        name: 'probe_communication',
        color: '0e9933',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-27T09:08:38Z',
    updated_at: '2017-06-27T09:12:41Z',
    closed_at: null,
    body: 'Spec: \r\n"user shall be aware at all time of the probe status (running, stanby , offline )" \r\n\r\n"user should be aware at all time of the connection state(disconnected, connected) between mobile application and probe"\r\n\r\n"user should be aware at all time of the probe battery level (full, medium, low) "\r\n\r\nStory Size(S/M/L/XL): L\r\n\r\nAcceptance criteria: \r\n* Mobile application code implemented and integrated \r\n* Probe emulator code implemented and integrated \r\n* integrated tests \r\n* Document communication with the probe ',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/53',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/53/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/53/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/53/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/53',
    id: 238779521,
    number: 53,
    title: 'Create user incident/assistance form',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 429061095,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/feature%20request',
        name: 'feature request',
        color: '8cf073',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-27T08:50:48Z',
    updated_at: '2017-06-27T08:52:06Z',
    closed_at: null,
    body: 'Spec: "user shall be able to notice echOpen team in case of incident occurring during usage."\r\n\r\nTo do so, we consider to implement an assistance form but other solutions can be discussed \r\n\r\nStory size(S/M/L/XL): M\r\n\r\nAcceptance criteria:\r\n* code implemented and integrated \r\n* document user support process\r\n* unit tests \r\n',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/52',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/52/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/52/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/52/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/52',
    id: 238777672,
    number: 52,
    title: 'Review previously saved images and loops',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 429061095,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/feature%20request',
        name: 'feature request',
        color: '8cf073',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-27T08:43:29Z',
    updated_at: '2017-06-27T08:43:54Z',
    closed_at: null,
    body: 'Spec: \r\n" user can review images and loops previously saved by application"\r\n\r\nStory size(S/M/L/XL): M\r\n\r\nAcceptance criteria: \r\n* code implemented and integrated \r\n* architecture design documentation updated\r\n* unit tests',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/51',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/51/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/51/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/51/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/51',
    id: 238776046,
    number: 51,
    title: 'Save an echography image loop',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 265844218,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/data',
        name: 'data',
        color: '009800',
        default: false,
      },
      {
        id: 429061095,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/feature%20request',
        name: 'feature request',
        color: '8cf073',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-27T08:36:58Z',
    updated_at: '2017-06-27T08:37:15Z',
    closed_at: null,
    body: 'Spec: \r\n"User can save an echography image loop lasting 5 seconds using DICOM format (to be detailed)"\r\n\r\nStory Size(S/M/L/XL) : M\r\n\r\nAcceptance criteria: \r\n* code implemented and integrated\r\n* architecture design documentation updated\r\n* DICOM export format created/updated\r\n* unit tests',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/50',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/50/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/50/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/50/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/50',
    id: 238774808,
    number: 50,
    title: 'Save a screen capture',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 265844218,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/data',
        name: 'data',
        color: '009800',
        default: false,
      },
      {
        id: 429061095,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/feature%20request',
        name: 'feature request',
        color: '8cf073',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-27T08:31:59Z',
    updated_at: '2017-06-27T08:33:02Z',
    closed_at: null,
    body: 'Spec: \r\n"user can save the current displayed echography image user using DICOM format (to be detailed)"\r\n\r\nStory Size(S/M/L/XL): M\r\n\r\nAcceptance criteria:\r\n* code implemented and integrated \r\n* architecture design documentation updated\r\n* DICOM export format document created/updated\r\n* unit tests ',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/49',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/49/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/49/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/49/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/49',
    id: 238773377,
    number: 49,
    title: 'Freeze application and review image by image',
    user: {
      login: 'clecoued',
      id: 4691525,
      avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/clecoued',
      html_url: 'https://github.com/clecoued',
      followers_url: 'https://api.github.com/users/clecoued/followers',
      following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
      gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
      organizations_url: 'https://api.github.com/users/clecoued/orgs',
      repos_url: 'https://api.github.com/users/clecoued/repos',
      events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
      received_events_url: 'https://api.github.com/users/clecoued/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 429061095,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/feature%20request',
        name: 'feature request',
        color: '8cf073',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-27T08:26:23Z',
    updated_at: '2017-06-27T08:27:05Z',
    closed_at: null,
    body: 'Spec: \r\n" user can freeze echography image streaming and review step by step, images received from the probe during the last 10 secondes"\r\n\r\nStory Size (S/M/L/XL) : S\r\n\r\nAcceptance Criteria: \r\n* code implemented and integrated in master branch \r\n* architecture design documentation updated\r\n* unit tests \r\n',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/45',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/45/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/45/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/45/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/45',
    id: 233882423,
    number: 45,
    title: 'emulating data in the app',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 429061095,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/feature%20request',
        name: 'feature request',
        color: '8cf073',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-06-06T12:55:23Z',
    updated_at: '2017-06-06T12:55:40Z',
    closed_at: null,
    body: 'in the [PR](https://github.com/echopen/PRJ-medtec_androidapp/pull/28) of @jerome2echopen, image are emulated through data provided by a `redpitaya` electronic board. The idea is here to emulate these data on your local machine without any call to `redpitaya` or other devices',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/42',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/42/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/42/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/42/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/42',
    id: 229710488,
    number: 42,
    title: 'Branch documentation ',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 265844046,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/documentation',
        name: 'documentation',
        color: '207de5',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    assignees: [
      {
        login: 'benchoufi',
        id: 1414193,
        avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/benchoufi',
        html_url: 'https://github.com/benchoufi',
        followers_url: 'https://api.github.com/users/benchoufi/followers',
        following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
        gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
        organizations_url: 'https://api.github.com/users/benchoufi/orgs',
        repos_url: 'https://api.github.com/users/benchoufi/repos',
        events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
        received_events_url: 'https://api.github.com/users/benchoufi/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
    milestone: null,
    comments: 0,
    created_at: '2017-05-18T15:16:29Z',
    updated_at: '2017-05-18T15:16:29Z',
    closed_at: null,
    body: 'Adding a description of branches, where good stuff can be found, UI, some apps where standalone environnement are set, which facilitates the development on focusing without carrying about superfluous code',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/40',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/40/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/40/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/40/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/40',
    id: 222442345,
    number: 40,
    title: 'tagging branch old and new',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 220189045,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/critical',
        name: 'critical',
        color: 'F20723',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    assignees: [
      {
        login: 'benchoufi',
        id: 1414193,
        avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/benchoufi',
        html_url: 'https://github.com/benchoufi',
        followers_url: 'https://api.github.com/users/benchoufi/followers',
        following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
        gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
        organizations_url: 'https://api.github.com/users/benchoufi/orgs',
        repos_url: 'https://api.github.com/users/benchoufi/repos',
        events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
        received_events_url: 'https://api.github.com/users/benchoufi/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
    milestone: null,
    comments: 0,
    created_at: '2017-04-18T14:49:10Z',
    updated_at: '2017-04-18T14:49:10Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/38',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/38/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/38/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/38/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/38',
    id: 219668888,
    number: 38,
    title: 'documenting SPECS',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 265844046,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/documentation',
        name: 'documentation',
        color: '207de5',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-04-05T18:09:28Z',
    updated_at: '2017-04-05T18:10:04Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/37',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/37/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/37/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/37/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/37',
    id: 219668818,
    number: 37,
    title: 'Intensity to RGB 16bits filter',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 201170780,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/enhancement',
        name: 'enhancement',
        color: '84b6eb',
        default: true,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-04-05T18:09:13Z',
    updated_at: '2017-04-05T18:10:29Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/36',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/36/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/36/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/36/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/36',
    id: 219668717,
    number: 36,
    title: 'fixing scanconversion parameters : center, radius, angle aperture',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 577333064,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/algorithms',
        name: 'algorithms',
        color: '0052cc',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-04-05T18:08:47Z',
    updated_at: '2017-04-05T18:13:18Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/34',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/34/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/34/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/34/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/34',
    id: 219668533,
    number: 34,
    title: 'adapting TCP pipeline to rendering local file data',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 201170780,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/enhancement',
        name: 'enhancement',
        color: '84b6eb',
        default: true,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-04-05T18:08:07Z',
    updated_at: '2017-04-05T18:13:54Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/33',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/33/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/33/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/33/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/33',
    id: 219668257,
    number: 33,
    title: 'merging OpenGL logic app into master branch app',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 201170780,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/enhancement',
        name: 'enhancement',
        color: '84b6eb',
        default: true,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-04-05T18:07:01Z',
    updated_at: '2017-04-05T18:14:34Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/32',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/32/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/32/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/32/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/32',
    id: 219663202,
    number: 32,
    title: 'documenting code',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 220189045,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/critical',
        name: 'critical',
        color: 'F20723',
        default: false,
      },
      {
        id: 265844046,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/documentation',
        name: 'documentation',
        color: '207de5',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-04-05T17:48:25Z',
    updated_at: '2017-04-05T18:14:49Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/31',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/31/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/31/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/31/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/31',
    id: 219662986,
    number: 31,
    title: 'documenting high level App logic',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 265844046,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/documentation',
        name: 'documentation',
        color: '207de5',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    assignees: [
      {
        login: 'benchoufi',
        id: 1414193,
        avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/benchoufi',
        html_url: 'https://github.com/benchoufi',
        followers_url: 'https://api.github.com/users/benchoufi/followers',
        following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
        gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
        organizations_url: 'https://api.github.com/users/benchoufi/orgs',
        repos_url: 'https://api.github.com/users/benchoufi/repos',
        events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
        received_events_url: 'https://api.github.com/users/benchoufi/received_events',
        type: 'User',
        site_admin: false,
      },
      {
        login: 'clecoued',
        id: 4691525,
        avatar_url: 'https://avatars0.githubusercontent.com/u/4691525?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/clecoued',
        html_url: 'https://github.com/clecoued',
        followers_url: 'https://api.github.com/users/clecoued/followers',
        following_url: 'https://api.github.com/users/clecoued/following{/other_user}',
        gists_url: 'https://api.github.com/users/clecoued/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/clecoued/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/clecoued/subscriptions',
        organizations_url: 'https://api.github.com/users/clecoued/orgs',
        repos_url: 'https://api.github.com/users/clecoued/repos',
        events_url: 'https://api.github.com/users/clecoued/events{/privacy}',
        received_events_url: 'https://api.github.com/users/clecoued/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
    milestone: null,
    comments: 0,
    created_at: '2017-04-05T17:47:32Z',
    updated_at: '2017-04-05T18:15:01Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/30',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/30/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/30/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/30/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/30',
    id: 218870325,
    number: 30,
    title: 'Phaino',
    user: {
      login: 'sjarso',
      id: 8423075,
      avatar_url: 'https://avatars2.githubusercontent.com/u/8423075?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/sjarso',
      html_url: 'https://github.com/sjarso',
      followers_url: 'https://api.github.com/users/sjarso/followers',
      following_url: 'https://api.github.com/users/sjarso/following{/other_user}',
      gists_url: 'https://api.github.com/users/sjarso/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/sjarso/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/sjarso/subscriptions',
      organizations_url: 'https://api.github.com/users/sjarso/orgs',
      repos_url: 'https://api.github.com/users/sjarso/repos',
      events_url: 'https://api.github.com/users/sjarso/events{/privacy}',
      received_events_url: 'https://api.github.com/users/sjarso/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [

    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 1,
    created_at: '2017-04-03T09:03:33Z',
    updated_at: '2017-05-06T10:30:02Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/pulls/30',
      html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/30',
      diff_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/30.diff',
      patch_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/30.patch',
    },
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/28',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/28/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/28/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/28/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/28',
    id: 213548874,
    number: 28,
    title: 'adding RedPitaya emulator',
    user: {
      login: 'GG23800',
      id: 14290878,
      avatar_url: 'https://avatars2.githubusercontent.com/u/14290878?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/GG23800',
      html_url: 'https://github.com/GG23800',
      followers_url: 'https://api.github.com/users/GG23800/followers',
      following_url: 'https://api.github.com/users/GG23800/following{/other_user}',
      gists_url: 'https://api.github.com/users/GG23800/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/GG23800/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/GG23800/subscriptions',
      organizations_url: 'https://api.github.com/users/GG23800/orgs',
      repos_url: 'https://api.github.com/users/GG23800/repos',
      events_url: 'https://api.github.com/users/GG23800/events{/privacy}',
      received_events_url: 'https://api.github.com/users/GG23800/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [

    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2017-03-11T18:28:02Z',
    updated_at: '2017-05-06T10:30:00Z',
    closed_at: null,
    pull_request: {
      url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/pulls/28',
      html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/28',
      diff_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/28.diff',
      patch_url: 'https://github.com/echopen/PRJ-medtec_androidapp/pull/28.patch',
    },
    body: 'My first pull request',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/27',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/27/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/27/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/27/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/27',
    id: 212210831,
    number: 27,
    title: 'implementing simulated data for TCP mocking',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 265844218,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/data',
        name: 'data',
        color: '009800',
        default: false,
      },
      {
        id: 577335817,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/test',
        name: 'test',
        color: '0e8a16',
        default: false,
      },
    ],
    state: 'open',
    locked: false,
    assignee: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    assignees: [
      {
        login: 'benchoufi',
        id: 1414193,
        avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/benchoufi',
        html_url: 'https://github.com/benchoufi',
        followers_url: 'https://api.github.com/users/benchoufi/followers',
        following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
        gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
        organizations_url: 'https://api.github.com/users/benchoufi/orgs',
        repos_url: 'https://api.github.com/users/benchoufi/repos',
        events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
        received_events_url: 'https://api.github.com/users/benchoufi/received_events',
        type: 'User',
        site_admin: false,
      },
    ],
    milestone: null,
    comments: 0,
    created_at: '2017-03-06T18:36:11Z',
    updated_at: '2017-04-05T18:16:38Z',
    closed_at: null,
    body: '',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/23',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/23/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/23/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/23/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/23',
    id: 190805249,
    number: 23,
    title: 'test suite failing with gradlew',
    user: {
      login: 'benchoufi',
      id: 1414193,
      avatar_url: 'https://avatars3.githubusercontent.com/u/1414193?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/benchoufi',
      html_url: 'https://github.com/benchoufi',
      followers_url: 'https://api.github.com/users/benchoufi/followers',
      following_url: 'https://api.github.com/users/benchoufi/following{/other_user}',
      gists_url: 'https://api.github.com/users/benchoufi/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/benchoufi/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/benchoufi/subscriptions',
      organizations_url: 'https://api.github.com/users/benchoufi/orgs',
      repos_url: 'https://api.github.com/users/benchoufi/repos',
      events_url: 'https://api.github.com/users/benchoufi/events{/privacy}',
      received_events_url: 'https://api.github.com/users/benchoufi/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 201170778,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/bug',
        name: 'bug',
        color: 'F20723',
        default: true,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 0,
    created_at: '2016-11-21T18:56:51Z',
    updated_at: '2016-11-21T19:01:37Z',
    closed_at: null,
    body: 'On Android Studio, the tests suit runs well. But when, launching it on TravisCI, I had issues as documenteed below. So that, I ran on my local machine `./gradlew clean build connectedCheck`, and I get this \r\n\r\n`com.echopen.asso.echopen.MainActivityTest > testBareMainViewsExists[Galaxy_Nexus_API_22(AVD) - 5.1] FAILED \r\n\tandroid.support.test.espresso.AppNotIdleException: Looped for 56 iterations over 60 SECONDS. The following Idle Conditions failed ASYNC_TASKS_HAVE_IDLED.\r\n\tat dalvik.system.VMStack.getThreadStackTrace(Native Method)\r\n\r\ncom.echopen.asso.echopen.MainActivityTest > testLayoutBackgroundColor[Galaxy_Nexus_API_22(AVD) - 5.1] FAILED \r\n\tandroid.support.test.espresso.AppNotIdleException: Looped for 30 iterations over 60 SECONDS. The following Idle Conditions failed ASYNC_TASKS_HAVE_IDLED.\r\n\tat dalvik.system.VMStack.getThreadStackTrace(Native Method)\r\n\r\ncom.echopen.asso.echopen.MainActivityTest > testMainViewsExists[Galaxy_Nexus_API_22(AVD) - 5.1] FAILED \r\n\tandroid.support.test.espresso.AppNotIdleException: Looped for 38 iterations over 60 SECONDS. The following Idle Conditions failed ASYNC_TASKS_HAVE_IDLED.\r\n\tat dalvik.system.VMStack.getThreadStackTrace(Native Method)\r\n\r\ncom.echopen.asso.echopen.MainActivityTest > testMeasureTextViewIsVisible[Galaxy_Nexus_API_22(AVD) - 5.1] FAILED \r\n\tandroid.support.test.espresso.AppNotIdleException: Looped for 43 iterations over 60 SECONDS. The following Idle Conditions failed ASYNC_TASKS_HAVE_IDLED.\r\n\tat dalvik.system.VMStack.getThreadStackTrace(Native Method)\r\n:app:connectedDebugAndroidTest FAILED` \r\n\r\nAnyone gets an idea ? \r\n\r\n',
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/21',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/21/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/21/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/21/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/21',
    id: 172261290,
    number: 21,
    title: 'Problem while executing app:cleanNative',
    user: {
      login: 'nameispriyank',
      id: 8774124,
      avatar_url: 'https://avatars0.githubusercontent.com/u/8774124?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/nameispriyank',
      html_url: 'https://github.com/nameispriyank',
      followers_url: 'https://api.github.com/users/nameispriyank/followers',
      following_url: 'https://api.github.com/users/nameispriyank/following{/other_user}',
      gists_url: 'https://api.github.com/users/nameispriyank/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/nameispriyank/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/nameispriyank/subscriptions',
      organizations_url: 'https://api.github.com/users/nameispriyank/orgs',
      repos_url: 'https://api.github.com/users/nameispriyank/repos',
      events_url: 'https://api.github.com/users/nameispriyank/events{/privacy}',
      received_events_url: 'https://api.github.com/users/nameispriyank/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 201170778,
        url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/labels/bug',
        name: 'bug',
        color: 'F20723',
        default: true,
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 7,
    created_at: '2016-08-20T08:43:19Z',
    updated_at: '2016-08-22T07:04:15Z',
    closed_at: null,
    body: "Imported this project few days back, but I was facing issues while debugging.\nError Message: \n\nError:14:06:47.754 [ERROR] [system.err] C:\\Android\\sdk\\ndk-bundle\\build\\..\\build\\core\\build-local.mk:158: **\\* Android NDK: Aborting.    .  Stop.\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] \n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] \n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] \\* What went wrong:\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:cleanNative'.\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'C:\\Android\\sdk\\ndk-bundle\\ndk-build.cmd'' finished with non-zero exit value 2\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] \n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] \\* Exception is:\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:cleanNative'.\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)\n14:06:47.759 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Factories$1.create(Factories.java:22)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)\n14:06:47.760 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.util.Swapper.swap(Swapper.java:38)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)\n14:06:47.761 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\\Android\\sdk\\ndk-bundle\\ndk-build.cmd'' finished with non-zero exit value 2\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:54)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter]    ... 70 more\n14:06:47.762 [ERROR] [org.gradle.BuildExceptionReporter] \n### _Build was successful, debugging only was causing problem_\n",
  },
  {
    url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/14',
    repository_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp',
    labels_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/14/labels{/name}',
    comments_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/14/comments',
    events_url: 'https://api.github.com/repos/echopen/PRJ-medtec_androidapp/issues/14/events',
    html_url: 'https://github.com/echopen/PRJ-medtec_androidapp/issues/14',
    id: 153573519,
    number: 14,
    title: 'Generate ultrasound with data',
    user: {
      login: 'winster',
      id: 2383613,
      avatar_url: 'https://avatars2.githubusercontent.com/u/2383613?v=3',
      gravatar_id: '',
      url: 'https://api.github.com/users/winster',
      html_url: 'https://github.com/winster',
      followers_url: 'https://api.github.com/users/winster/followers',
      following_url: 'https://api.github.com/users/winster/following{/other_user}',
      gists_url: 'https://api.github.com/users/winster/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/winster/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/winster/subscriptions',
      organizations_url: 'https://api.github.com/users/winster/orgs',
      repos_url: 'https://api.github.com/users/winster/repos',
      events_url: 'https://api.github.com/users/winster/events{/privacy}',
      received_events_url: 'https://api.github.com/users/winster/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [

    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [

    ],
    milestone: null,
    comments: 10,
    created_at: '2016-05-07T04:50:57Z',
    updated_at: '2016-05-09T07:13:44Z',
    closed_at: null,
    body: 'First of all congrats and thanks a lot of this open source initiative. I am working on another open source Android library for ultrasound data transfer. Currently I have only audible sound based (ASK) version. Then I came across echopen.org and its android app. I believe you have ultrasound scanning with noise cancellation enabled in your Android app. Can I also generate ultrasound waves using Android so that we can embed data into it? May be this is something you would have tried to test your Android app.\n',
  },
];


export default issues;
