const Characters = [
  {
    x: 20,
    y: 17,
    s: 60,
    name: 'Jungle',
    imgPath: 'static/img/portrait1.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 20,
    y: 45,
    s: 80,
    name: 'Jungle',
    imgPath: 'static/img/portrait2.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 40,
    y: -1,
    s: 75,
    name: 'Jungle',
    imgPath: 'static/img/portrait3.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 50,
    y: 3,
    s: 50,
    name: 'Jungle',
    imgPath: 'static/img/portrait4.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 60,
    y: 0,
    s: 90,
    name: 'Jungle',
    imgPath: 'static/img/portrait5.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 75,
    y: 17,
    s: 90,
    name: 'Jungle',
    imgPath: 'static/img/portrait6.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 73,
    y: 70,
    s: 90,
    name: 'Jungle',
    imgPath: 'static/img/portrait7.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 57,
    y: 75,
    s: 50,
    name: 'Jungle',
    imgPath: 'static/img/portrait7.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 50,
    y: 80,
    s: 60,
    name: 'Jungle',
    imgPath: 'static/img/portrait8.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 80,
    y: 60,
    s: 60,
    name: 'Jungle',
    imgPath: 'static/img/portrait9.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 28,
    y: 70,
    s: 70,
    name: 'Jungle',
    imgPath: 'static/img/portrait10.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 30,
    y: 50,
    s: 45,
    name: 'Jungle',
    imgPath: 'static/img/portrait11.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 65,
    y: 40,
    s: 60,
    name: 'Jungle',
    imgPath: 'static/img/portrait12.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
  {
    x: 15,
    y: 5,
    s: 50,
    name: 'Jungle',
    imgPath: 'static/img/portrait1.png',
    description: '“ Participer à EchoPen est pour moi une aventure extraordinaire, riche de rencontres, d’envie. L’objectif rendu par EchoPen est complètement dingue” ',
  },
];

export default Characters;
